branches: [release]
name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: 'Semantic Version Major'
    labels:
      - 'needs version bump'
  - title: 'Semantic Version Minor'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Other Changes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
