#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2019-2021 Paul Schmiedmayer and the Apodini project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#


module: Apodini
author: Paul Schmiedmayer
theme: fullwidth
output: ./docs
documentation: ./*.md
author_url: https://github.com/Apodini
github_url: https://github.com/Apodini/Apodini
