ignore:
- "Tests"
- "Sources/TestWebService"

codecov:
  require_ci_to_pass: yes

coverage:
  range: "60...90"
  precision: 2
  round: up
  status:
    # The project status measures overall project coverage and compares it against the base of the pull request
    project:
      default:
        # Choose a minimum coverage ratio that the commit must meet to be considered a success
        target: auto
        # Allow the coverage to drop by X%, and posting a success status.
        threshold: 0%
    # The patch status only measures lines adjusted in the pull request
    patch:
      default:
        # Choose a minimum coverage ratio that the commit must meet to be considered a success
        target: auto
        # Allow the coverage to drop by X%, and posting a success status.
        threshold: 15%  

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
