#!/usr/bin/env fish


set idx 0

while true;
    echo "Loop #$idx"
    set idx (math $idx + 1)
    if swift test --filter 'GRPCInterfaceExporterTests.testBidirectionalStream';;
    else;
        echo "it failed"
        exit 1
    end
end

# while swift test --filter 'GRPCInterfaceExporterTests.testBidirectionalStream'; ; end

