// swiftlint:disable all
// This file was automatically generated and should not be edited.

@resultBuilder
public struct RelationshipIdentificationBuilder<From> {
    public static func buildBlock<To0: Identifiable>(_ identification0: RelationshipIdentification<From, To0>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable, To4: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>, _ identification4: RelationshipIdentification<From, To4>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3), AnyRelationshipIdentification(from: identification4)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable, To4: Identifiable, To5: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>, _ identification4: RelationshipIdentification<From, To4>, _ identification5: RelationshipIdentification<From, To5>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3), AnyRelationshipIdentification(from: identification4), AnyRelationshipIdentification(from: identification5)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable, To4: Identifiable, To5: Identifiable, To6: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>, _ identification4: RelationshipIdentification<From, To4>, _ identification5: RelationshipIdentification<From, To5>, _ identification6: RelationshipIdentification<From, To6>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3), AnyRelationshipIdentification(from: identification4), AnyRelationshipIdentification(from: identification5), AnyRelationshipIdentification(from: identification6)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable, To4: Identifiable, To5: Identifiable, To6: Identifiable, To7: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>, _ identification4: RelationshipIdentification<From, To4>, _ identification5: RelationshipIdentification<From, To5>, _ identification6: RelationshipIdentification<From, To6>, _ identification7: RelationshipIdentification<From, To7>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3), AnyRelationshipIdentification(from: identification4), AnyRelationshipIdentification(from: identification5), AnyRelationshipIdentification(from: identification6), AnyRelationshipIdentification(from: identification7)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable, To4: Identifiable, To5: Identifiable, To6: Identifiable, To7: Identifiable, To8: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>, _ identification4: RelationshipIdentification<From, To4>, _ identification5: RelationshipIdentification<From, To5>, _ identification6: RelationshipIdentification<From, To6>, _ identification7: RelationshipIdentification<From, To7>, _ identification8: RelationshipIdentification<From, To8>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3), AnyRelationshipIdentification(from: identification4), AnyRelationshipIdentification(from: identification5), AnyRelationshipIdentification(from: identification6), AnyRelationshipIdentification(from: identification7), AnyRelationshipIdentification(from: identification8)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable, To4: Identifiable, To5: Identifiable, To6: Identifiable, To7: Identifiable, To8: Identifiable, To9: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>, _ identification4: RelationshipIdentification<From, To4>, _ identification5: RelationshipIdentification<From, To5>, _ identification6: RelationshipIdentification<From, To6>, _ identification7: RelationshipIdentification<From, To7>, _ identification8: RelationshipIdentification<From, To8>, _ identification9: RelationshipIdentification<From, To9>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3), AnyRelationshipIdentification(from: identification4), AnyRelationshipIdentification(from: identification5), AnyRelationshipIdentification(from: identification6), AnyRelationshipIdentification(from: identification7), AnyRelationshipIdentification(from: identification8), AnyRelationshipIdentification(from: identification9)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable, To4: Identifiable, To5: Identifiable, To6: Identifiable, To7: Identifiable, To8: Identifiable, To9: Identifiable, To10: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>, _ identification4: RelationshipIdentification<From, To4>, _ identification5: RelationshipIdentification<From, To5>, _ identification6: RelationshipIdentification<From, To6>, _ identification7: RelationshipIdentification<From, To7>, _ identification8: RelationshipIdentification<From, To8>, _ identification9: RelationshipIdentification<From, To9>, _ identification10: RelationshipIdentification<From, To10>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3), AnyRelationshipIdentification(from: identification4), AnyRelationshipIdentification(from: identification5), AnyRelationshipIdentification(from: identification6), AnyRelationshipIdentification(from: identification7), AnyRelationshipIdentification(from: identification8), AnyRelationshipIdentification(from: identification9), AnyRelationshipIdentification(from: identification10)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable, To4: Identifiable, To5: Identifiable, To6: Identifiable, To7: Identifiable, To8: Identifiable, To9: Identifiable, To10: Identifiable, To11: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>, _ identification4: RelationshipIdentification<From, To4>, _ identification5: RelationshipIdentification<From, To5>, _ identification6: RelationshipIdentification<From, To6>, _ identification7: RelationshipIdentification<From, To7>, _ identification8: RelationshipIdentification<From, To8>, _ identification9: RelationshipIdentification<From, To9>, _ identification10: RelationshipIdentification<From, To10>, _ identification11: RelationshipIdentification<From, To11>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3), AnyRelationshipIdentification(from: identification4), AnyRelationshipIdentification(from: identification5), AnyRelationshipIdentification(from: identification6), AnyRelationshipIdentification(from: identification7), AnyRelationshipIdentification(from: identification8), AnyRelationshipIdentification(from: identification9), AnyRelationshipIdentification(from: identification10), AnyRelationshipIdentification(from: identification11)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable, To4: Identifiable, To5: Identifiable, To6: Identifiable, To7: Identifiable, To8: Identifiable, To9: Identifiable, To10: Identifiable, To11: Identifiable, To12: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>, _ identification4: RelationshipIdentification<From, To4>, _ identification5: RelationshipIdentification<From, To5>, _ identification6: RelationshipIdentification<From, To6>, _ identification7: RelationshipIdentification<From, To7>, _ identification8: RelationshipIdentification<From, To8>, _ identification9: RelationshipIdentification<From, To9>, _ identification10: RelationshipIdentification<From, To10>, _ identification11: RelationshipIdentification<From, To11>, _ identification12: RelationshipIdentification<From, To12>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3), AnyRelationshipIdentification(from: identification4), AnyRelationshipIdentification(from: identification5), AnyRelationshipIdentification(from: identification6), AnyRelationshipIdentification(from: identification7), AnyRelationshipIdentification(from: identification8), AnyRelationshipIdentification(from: identification9), AnyRelationshipIdentification(from: identification10), AnyRelationshipIdentification(from: identification11), AnyRelationshipIdentification(from: identification12)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable, To4: Identifiable, To5: Identifiable, To6: Identifiable, To7: Identifiable, To8: Identifiable, To9: Identifiable, To10: Identifiable, To11: Identifiable, To12: Identifiable, To13: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>, _ identification4: RelationshipIdentification<From, To4>, _ identification5: RelationshipIdentification<From, To5>, _ identification6: RelationshipIdentification<From, To6>, _ identification7: RelationshipIdentification<From, To7>, _ identification8: RelationshipIdentification<From, To8>, _ identification9: RelationshipIdentification<From, To9>, _ identification10: RelationshipIdentification<From, To10>, _ identification11: RelationshipIdentification<From, To11>, _ identification12: RelationshipIdentification<From, To12>, _ identification13: RelationshipIdentification<From, To13>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3), AnyRelationshipIdentification(from: identification4), AnyRelationshipIdentification(from: identification5), AnyRelationshipIdentification(from: identification6), AnyRelationshipIdentification(from: identification7), AnyRelationshipIdentification(from: identification8), AnyRelationshipIdentification(from: identification9), AnyRelationshipIdentification(from: identification10), AnyRelationshipIdentification(from: identification11), AnyRelationshipIdentification(from: identification12), AnyRelationshipIdentification(from: identification13)]
    }

    public static func buildBlock<To0: Identifiable, To1: Identifiable, To2: Identifiable, To3: Identifiable, To4: Identifiable, To5: Identifiable, To6: Identifiable, To7: Identifiable, To8: Identifiable, To9: Identifiable, To10: Identifiable, To11: Identifiable, To12: Identifiable, To13: Identifiable, To14: Identifiable>(_ identification0: RelationshipIdentification<From, To0>, _ identification1: RelationshipIdentification<From, To1>, _ identification2: RelationshipIdentification<From, To2>, _ identification3: RelationshipIdentification<From, To3>, _ identification4: RelationshipIdentification<From, To4>, _ identification5: RelationshipIdentification<From, To5>, _ identification6: RelationshipIdentification<From, To6>, _ identification7: RelationshipIdentification<From, To7>, _ identification8: RelationshipIdentification<From, To8>, _ identification9: RelationshipIdentification<From, To9>, _ identification10: RelationshipIdentification<From, To10>, _ identification11: RelationshipIdentification<From, To11>, _ identification12: RelationshipIdentification<From, To12>, _ identification13: RelationshipIdentification<From, To13>, _ identification14: RelationshipIdentification<From, To14>) -> [AnyRelationshipIdentification] {
        [AnyRelationshipIdentification(from: identification0), AnyRelationshipIdentification(from: identification1), AnyRelationshipIdentification(from: identification2), AnyRelationshipIdentification(from: identification3), AnyRelationshipIdentification(from: identification4), AnyRelationshipIdentification(from: identification5), AnyRelationshipIdentification(from: identification6), AnyRelationshipIdentification(from: identification7), AnyRelationshipIdentification(from: identification8), AnyRelationshipIdentification(from: identification9), AnyRelationshipIdentification(from: identification10), AnyRelationshipIdentification(from: identification11), AnyRelationshipIdentification(from: identification12), AnyRelationshipIdentification(from: identification13), AnyRelationshipIdentification(from: identification14)]
    }

}
