#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2019-2021 Paul Schmiedmayer and the Apodini project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Build

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    uses: Apodini/Apodini/.github/workflows/build-and-test.yml@feature/ciimprovements
    with:
      packagename: Apodini
      codecoverage: true
  build_and_test_web_service:
    name: Build and Test Test Web Service
    uses: Apodini/Apodini/.github/workflows/build-and-test.yml@feature/ciimprovements
    with:
      path: ./TestWebService
      packagename: TestWebService
