#                   
# This source file is part of the Apodini Template open source project
# 
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
# 
# SPDX-License-Identifier: MIT
# 

name: Docker Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dockercompose:
    name: Docker Compose Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose -f docker-compose-development.yml up -d --build
      - name: Test web service
        run: |
          sleep 3
          sh TestWebService/test.sh
      - name: Stop containers
        if: always()
        run: docker-compose down
