#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2019-2021 Paul Schmiedmayer and the Apodini project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Push

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    uses: Apodini/.github/.github/workflows/build-and-test.yml@feature/macos11
    with:
      packagename: Apodini
      testdocc: true
      aptgetdependencies: libsqlite3-dev
      yumdependencies: sqlite-devel
  test_web_service:
    name: Test Web Service
    uses: Apodini/Apodini/.github/workflows/test-web-service.yml@feature/ciimprovements
  docker-compose-test:
    name: Docker Test
    uses: Apodini/.github/.github/workflows/docker-compose-test.yml@feature/macos11
    with:
      testscript: TestWebService/test.sh
