#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2019-2021 Paul Schmiedmayer and the Apodini project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Push

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    uses: Apodini/.github/.github/workflows/build-and-test.yml@main
    with:
      packagename: Apodini
      aptgetdependencies: libsqlite3-dev
      yumdependencies: sqlite-devel
      installgrpcurl: true
  docker-compose-test:
    name: Docker Compose Test
    uses: Apodini/.github/.github/workflows/docker-compose-test.yml@v1
    with:
      testscript: TestWebService/test.sh
