#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2019-2021 Paul Schmiedmayer and the Apodini project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    name: Generate Docs
    uses: Apodini/.github/.github/workflows/docs.yml@v1
    with:
      targetname: Apodini
  docker-build-and-push:
    name: Docker Build and Push
    uses: Apodini/.github/.github/workflows/docker-build-and-push.yml@v1
    with:
      image-name: apodini/testwebservice
      docker-file: ./TestWebService/Dockerfile
