#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Run TestWebService

on:
  pull_request:
  push:
    branches:
      - develop
  workflow_call:
  workflow_dispatch:

jobs:
  macos:
    name: macOS ${{ matrix.configuration }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        configuration: [debug, release]
    defaults:
      run:
        working-directory: TestWebService
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: TestWebService/.build
        key: ${{ runner.os }}-spm-tws-${{ hashFiles('**/Package.resolved') }}
    - uses: maxim-lobanov/setup-xcode@v1.4.0
      with:
        xcode-version: latest-stable
    - name: Check environment
      run: |
          xcodebuild -version
          swift --version
    - name: Run ${{ matrix.configuration }} build
      run: swift build -c ${{ matrix.configuration }}
    - name: Check Resources
      run: |
        ls -l ./.build/debug/TestWebService_TestWebService.bundle
    - name: Test HTTP/1.1
      run: |
          exec 3< <(swift run -c ${{ matrix.configuration }})
          sed '/info org.apodini.application : Server starting on/q' <&3 ; cat <&3 &
          bash test.sh
      shell: bash
    - name: Kill port 80 TestWebService
      run: kill -9 $(lsof -ti:80)
      shell: bash
    - name: Test HTTP/2
      run: |
          swift run -c ${{ matrix.configuration }} TestWebService --https-config builtin --port 4443 &
          sleep 15
# sh testhttp2.sh
      shell: bash
    - name: Kill port 4443 TestWebService
      run: kill -9 $(lsof -ti:4443)
      shell: bash
  linux:
    name: Linux ${{ matrix.linux }} ${{ matrix.configuration }}
    container:
      image: swift:${{ matrix.linux }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linux: [focal, amazonlinux2]
        configuration: [debug, release]
    defaults:
      run:
        working-directory: TestWebService
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: TestWebService/.build
        key: ${{ runner.os }}-${{ matrix.linux }}-spm-tws-${{ hashFiles('Package.resolved') }}
    - name: Check environment
      run: swift --version
    - name: Install apt-get Dependencies
      if: matrix.linux != 'centos8' && matrix.linux != 'amazonlinux2'
      run: apt-get update && apt-get install -y --no-install-recommends curl lsof
    - name: Install yum Dependencies
      if: matrix.linux == 'amazonlinux2'
      run: yum update -y && yum install -y curl lsof python3
    - name: Install yum Dependencies
      if: matrix.linux == 'centos8'
      run: yum update -y --nobest && yum install -y curl lsof python3
    - name: Run ${{ matrix.configuration }} build
      run: swift build -c ${{ matrix.configuration }}
    - name: Check Resources
      run: |
        ls -l ./.build/debug/TestWebService_TestWebService.bundle
    - name: Test HTTP/1.1
      run: |
          exec 3< <(.build/${{ matrix.configuration }}/TestWebService)
          sed '/info org.apodini.application : Server starting on/q' <&3 ; cat <&3 &
          bash test.sh
      shell: bash
    - name: Kill port 80 TestWebService
      run: kill -9 $(lsof -ti:80)
      shell: bash
    - name: Test HTTP/2
      run: |
          exec 3< <(.build/${{ matrix.configuration }}/TestWebService --https-config builtin)
          sed '/info org.apodini.application : Server starting on/q' <&3 ; cat <&3 &
          bash testhttp2.sh
      shell: bash
    - name: Kill port 443 TestWebService
      run: kill -9 $(lsof -ti:443)
      shell: bash
