name: Sonarcloud
on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: latest
      - name: Install sonar-scanner
        run: brew install sonar-scanner
      - name: Generate Xcode Project
        run: swift package generate-xcodeproj
      - name: Run Tests
        run: xcodebuild -resultBundlePath Apodini.xcresult -scheme Apodini-Package test -enableCodeCoverage YES
      - name: Generate Coverage Report
        run: sh ./.github/workflows/sonarcloud.sh Apodini.xcresult > Apodini-Coverage.xml 2> /dev/null
      - name: Run SwiftLint
        run: swiftlint lint --reporter json > swiftlint.json
      - name: Run Sonar-Scan
        run: sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
