name: Sonarcloud
on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: latest
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-xcode-cachev2-${{ hashFiles('**/Package.resolved') }}
      - name: Install xcparse
        run: brew install chargepoint/xcparse/xcparse
      - name: Install sonar-scanner
        run: brew install sonar-scanner
      - name: Check Swift version
        run: swift --version
      - name: Generate Xcode Project
        run: swift package generate-xcodeproj
      - name: Run Tests
        run: xcodebuild -resultBundlePath Apodini.xcresult -scheme Apodini-Package test -enableCodeCoverage YES
      - name: Generate xccovarchive
        run: xcparse codecov Apodini.xcresult
      - name: Generate Coverage Report
        run: sh ./.github/workflows/sonarcloud.sh action.xccovarchive > Apodini-Coverage.xml
      - name: Run SwiftLint
        run: swiftlint lint --reporter json > swiftlint.json
      - name: Run Sonar-Scan
        run: sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
