name: Sonarcloud
on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: latest
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-xcode-cachev2-${{ hashFiles('**/Package.resolved') }}
      - name: Check Swift version
        run: swift --version
      - name: Generate Xcode Project
        run: swift package generate-xcodeproj
      - name: Run Tests
        run: xcodebuild -resultBundlePath Apodini.xcresult -scheme Apodini-Package test -enableCodeCoverage YES
      - name: Gather Test Coverage
        run: ./.github/workflows/cococo Apodini.xcresult > Apodini-Coverage.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
