name: Swift Package Update

on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:
  
jobs:
  createPR:
    name: Create Pull Request
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-cache-${{ hashFiles('Package.resolved') }}
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Update Swift Packages
      run: swift package update
    - uses: peter-evans/create-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        commit-message: Update dependencies
        title: Update dependencies
        body: |
          Update the Swift Package dependencies.
        branch: bots/update-dependencies
