name: Swift Package Update

on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:
  
jobs:
  createPR:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Swift version
      run: swift --version
    - name: Update Swift Packages
      run: swift package update
    - name: Update Swift Packages for Test WebService
      run: swift package update
      working-directory: ./TestWebService
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        commit-message: Update dependencies
        title: Update dependencies
        body: Update the Swift Package dependencies.
        delete-branch: true
        base: develop
        branch: bots/update-dependencies
        assignees: ApodiniBot
        committer: ApodiniBot <ApodiniBot@users.noreply.github.com>
        author: ApodiniBot <ApodiniBot@users.noreply.github.com>
        reviewers: PSchmiedmayer
