name: Test TestWebService

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release
      
defaults:
  run:
    working-directory: TestWebService

jobs:
  macos:
    name: macOS ${{ matrix.configuration }} test TestWebService
    runs-on: macos-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-cachev2-${{ hashFiles('Package.resolved') }}
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Build & Test
      run: swift test --configuration ${{ matrix.configuration }} --enable-test-discovery
  linux:
    name: Linux ${{ matrix.linux }} ${{ matrix.configuration }} test TestWebService
    container:
      image: swift:${{ matrix.linux }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux: [bionic, xenial, focal, amazonlinux2, centos8]
        configuration: [debug, release]
    steps:
    - uses: actions/checkout@v2
    - name: Install libsqlite3
      if: ${{ !(startsWith( matrix.linux, 'centos' ) || startsWith( matrix.linux, 'amazonlinux' )) }}
      run: apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev
    - name: Install libsqlite3
      if: ${{ startsWith( matrix.linux, 'centos' ) || startsWith( matrix.linux, 'amazonlinux' ) }}
      run: yum update -y && yum install -y sqlite-devel
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-${{matrix.linux}}-spm-cachev2-${{ hashFiles('Package.resolved') }}
    - name: Check Swift version
      run: swift --version
    - name: Build & Test
      run: swift test --configuration ${{ matrix.configuration }} --enable-test-discovery
